### ISSUE TITLE
"signal-handling" seems to be a wrong category

### ISSUE THREAD

**Issue by taiki-e** [smol-rs/async-signal#32]
Our Cargo.toml currently has the following categories:

https://github.com/smol-rs/async-signal/blob/b74019fc773fd23e76116e5aec92d2d4762079be/Cargo.toml#L11

However, on crates.io page, the category corresponding to "signal-handling" is not shown.
https://crates.io/crates/async-signal

<img width="216" alt="crates-io" src="https://github.com/smol-rs/async-signal/assets/43724913/cd1d430c-e53b-4271-9aad-6ec5404c83e9">

**Comment by notgull** [comment]
I think I meant to use the "signal" category here, but somehow I missed that.
